### ISSUE TITLE
Circumvention of reCaptcha Verification in Payment Process

### ISSUE THREAD

**Issue by Yuyan-Lei** [Privacy-and-Security/AuthGate_FE#10]
In the payment process, although we already implemented reCaptcha as a way to prevent bot attacks, this verification mechanism appears to be bypassable. 

Users can manipulate the webpage by using the browser's F12 developer tools, allowing them to proceed without entering the reCaptcha code.

 This could potentially pose security risks and facilitate fraudulent activities.

**Comment by Yuyan-Lei** [comment]
I guess addressing this issue may require backend modifications.

**Comment by Zhongyi-Lu** [comment]
Great comments and sugguestions! We have added validations for both frontend (https://github.com/Privacy-and-Security/AuthGate_FE/pull/14) and backend (https://github.com/Privacy-and-Security/AuthGate_Server/pull/2).
