### ISSUE TITLE
Lack of Input Validation in Payment Section on the Frontend Interface

### ISSUE THREAD

**Issue by Yuyan-Lei** [Privacy-and-Security/AuthGate_FE#11]
I have observed that there is a lack of input validation in the payment section of the frontend interface. 

Several payment information input fields on the interface do not have input content validation in place. 

For example, the CVV field does not restrict input to only three digits, and the expiration date does not strictly enforce the correct date format beyond the current date.

**Comment by Yuyan-Lei** [comment]
The expiry date part seems to be the most difficult one. We need to figure out a way to code the date format validation function. Any thoughts?

**Comment by Zhongyi-Lu** [comment]
Hi. Great comments. We should add validation in both the frontend and the backend. Date format should be "MM/YY".
