### ISSUE TITLE
Request for Preventing Brute-Force Attacks

### ISSUE THREAD

**Issue by Zhongyi-Lu** [Privacy-and-Security/AuthGate_FE#8]
I've noticed that our current login system might be susceptible to **brute-force attacks**. Could we consider implementing additional security measures to defend these threats?

**Comment by Yuyan-Lei** [comment]
Great question! I've actually enabled the brute-force protection feature within Auth0, which does an excellent job at defending against brute-force attacks on individual user accounts. Here's how our website works now:

A) Blocking Suspicious IP Addresses: When a particular IP address repeatedly attempts and fails to log in as the same user, our site automatically blocks that suspicious IP address from further login attempts for that specific user account.

B) Notification to Affected Users: Additionally, our site sends an email notification to the affected user, alerting them to suspicious login attempts. This provides an extra layer of security and keeps users informed about any potential security concerns.

I've tested this feature, and it has effectively addressed the issue of brute-force attacks on user accounts. Our login system is now better protected against such threats. 

If you have any more questions or concerns, please feel free to let me know!

**Comment by Yuyan-Lei** [comment]
Solved.
