### ISSUE TITLE
Encrypt Payment Information to Prevent Data Exposure

### ISSUE THREAD

**Issue by Zhongyi-Lu** [Privacy-and-Security/AuthGate_FE#9]
I found payment details are currently sent in **plain text**, risking data interception and exposure. Could we implement encryption to safeguard user data?

**Comment by Yuyan-Lei** [comment]
Great point! I'm keeping an eye on this issue.

**Comment by Yuyan-Lei** [comment]
Certainly, the issue you mentioned does indeed exist. I have just replicated the problem myself, confirming that payment information can indeed be intercepted. 

I will be making modifications to both the frontend and backend in the near future to attempt to address this issue.

<img width="724" alt="image" src="https://github.com/Privacy-and-Security/authGate/assets/82356933/32474def-f776-475e-8129-47e5b8f27a32">
